### ISSUE TITLE
OpenID Conformance Test Basic - OP-scope-profile

### ISSUE THREAD

**Issue by leleabhinav** [rohe/oidctest#140]
Running OP-scope-profile fails with the below trace - 

********************************************************************************

Something went wrong! If you know or suspect you know why, then try to
fix it. If you have no idea, then please tell us at certification@oidf.org
and we will help you figure it out.

********************************************************************************

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/oauth2/message.py", line 389, in _add_value
    self._dict[skey] = int(val)
ValueError: invalid literal for int() with base 10: '2019-08-21T19:19:04.000Z'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/otest-0.7.6-py3.6.egg/otest/aus/tool.py", line 95, in run_flow
    resp = _oper()
  File "/usr/local/lib/python3.6/dist-packages/otest-0.7.6-py3.6.egg/otest/operation.py", line 105, in __call__
    res = self.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/oidctest-0.7.5-py3.6.egg/oidctest/op/oper.py", line 356, in run
    **args)
  File "/usr/local/lib/python3.6/dist-packages/otest-0.7.6-py3.6.egg/otest/operation.py", line 171, in catch_exception_and_error
    res = func(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/oidctest-0.7.5-py3.6.egg/oidctest/op/oper.py", line 346, in do_user_info_request
    res = self.conv.entity.do_user_info_request(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/oidctest-0.7.5-py3.6.egg/oidctest/op/client.py", line 113, in do_user_info_request
    res = _schema().from_json(txt=_txt)
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/oauth2/message.py", line 469, in from_json
    return self.from_dict(json.loads(txt))
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/oauth2/message.py", line 359, in from_dict
    self._add_value(skey, vtyp, key, val, _deser, null_allowed)
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/oauth2/message.py", line 391, in _add_value
    raise ValueError('"{}", wrong type of value for "{}"'.format(val, skey))
ValueError: "2019-08-21T19:19:04.000Z", wrong type of value for "updated_at"

**Comment by rohe** [comment]
updated_at is supposed to be seconds since epoch. That is, an integer not a string.

**Comment by leleabhinav** [comment]
Thanks!
