### ISSUE TITLE
current continuous integration tests fails

### ISSUE THREAD

**Issue by zandbelt** [rohe/oidctest#45]
When I pull the changes since May 11th, the continuous integration tests from @panva fail on a number of tests:
```
62 passing (22s)
  2 pending
  5 failing
  1)  OP-IDToken-ES256:
      AssertionError: Expected to be on a result screen
      + expected - actual
      -/authz_post
      +/display
      
      at passed (test/helpers.js:26:10)
  2)  OP-IDToken-HS256:
      AssertionError: Expected to be on a result screen
      + expected - actual
      -/authz_post
      +/display
      
      at passed (test/helpers.js:26:10)
  3)  OP-IDToken-RS256:
      AssertionError: Expected to be on a result screen
      + expected - actual
      -/authz_post
      +/display
      
      at passed (test/helpers.js:26:10)
  4)  OP-claims-sub:
      AssertionError: Expected status to be Green, got Red
      + expected - actual
      -Red
      +Green
      
      at passed (test/helpers.js:33:10)
  5)  OP-redirect_uri-Query-OK:
      AssertionError: Expected status to be Green, got Red
      + expected - actual
      -Red
      +Green
      
      at passed (test/helpers.js:33:10)
```
Not sure but It looks like for 1-3 that the flow somehow changed and there's no intermediate screen anymore?

For 4 the problem seems to be caused by:
https://github.com/rohe/oidctest/commit/50d3e42ad5651410b3423f48f427cc87a94337db

For 5 the log says:
```
check-query-part: status=ERROR, message=The query component foo=bar not part of the response [Check that a query part send in the Authorization Request is returned in the Authorization response.]
```

**Comment by rohe** [comment]
Think I've fixed these now. 3 different bugs :-(

**Comment by zandbelt** [comment]
Almost there: 1-3 and 5 are OK now.  4 still says:
```
verify-sub-value: status=ERROR, message=No claims request in the Authorization request [Verifies that the sub claim returned in the id_token matched the one asked for.]
```

**Comment by zandbelt** [comment]
These all work now.
